const roles = [
  ["citizen","Fuqaro","town","Kechasi maxsus harakati yo‘q."],
  ["mafia","Mafiya","mafia","Mafiya jamoasi bilan nishon tanlaydi."],
  ["don","Don","mafia","Mafiya boshlig‘i; kechasi nishon tanlaydi."],
  ["doctor","Doktor","town","Bir o‘yinchini o‘limdan saqlaydi."],
  ["detective","Detektiv","town","Bir o‘yinchining jamoasini tekshiradi."],
  ["bodyguard","Qo‘riqchi","town","Tanlangan o‘yinchini himoya qiladi."],
  ["jailer","Qamoqchi","town","O‘yinchini bloklaydi va himoya qiladi."],
  ["silencer","Jim qiluvchi","mafia","Kunduzgi muloqotni cheklaydi."],
  ["consigliere","Maslahatchi","mafia","Don uchun rol ma’lumotini izlaydi."],
  ["framer","Soxtalashtiruvchi","mafia","Tekshiruv natijasini chalg‘itadi."],
  ["lawyer","Advokat","mafia","Mafiya a’zosini tekshiruvdan yashirishga yordam beradi."],
  ["blackmailer","Shantajchi","mafia","Kechasi tanlangan o‘yinchini jim qiladi."],
  ["tracker","Kuzatuvchi","town","O‘yinchi kimga harakat qilganini kuzatadi."],
  ["watcher","Guvoh","town","Kimlar tanlangan o‘yinchiga kelganini ko‘radi."],
  ["investigator","Tergovchi","town","Murakkab rol guruhini tekshiradi."],
  ["psychic","Ekstrasens","town","Tasodifiy yashirin ma’lumot oladi."],
  ["medium","Medium","town","O‘lganlar haqida cheklangan ma’lumot oladi."],
  ["seer","Ko‘ruvchi","town","Bitta o‘yinchining rolini aniqlashga urinadi."],
  ["oracle","Orakul","town","Kelgusi ovoz haqida signal oladi."],
  ["mayor","Mer","town","Ovoz berishda maxsus kuchga ega."],
  ["judge","Sudya","town","Ovoz natijasiga ta’sir qilishi mumkin."],
  ["veteran","Veteran","town","Hujum qilgan kechada o‘zini himoya qiladi."],
  ["hunter","Ovchi","town","O‘lganda bitta qarshi zarba beradi."],
  ["vigilante","Qasoskor","town","Kechasi bir nishonga hujum qilishi mumkin."],
  ["cop","Politsiyachi","town","Nishonning jamoasini tekshiradi."],
  ["doctor2","Field Doctor","town","Bir martalik kuchli himoya beradi."],
  ["escort","Yo‘ldosh","town","Nishonning tungi harakatini bloklaydi."],
  ["transport","Transportchi","town","Ikki o‘yinchining nishonlarini almashtiradi."],
  ["lookout","Kuzatuvchi","town","Bir nishonga kelganlarni ko‘radi."],
  ["sniper","Snayper","town","Cheklangan o‘q bilan kuchli hujum qiladi."],
  ["godfather","Godfather","mafia","Mafiya rahbari va tekshiruvdan yashirin."],
  ["mafioso","Mafioso","mafia","Mafiya hujumlarini bajaradi."],
  ["ninja","Ninja","mafia","Kuzatuvlardan yashirin harakat qiladi."],
  ["consort","Mafiya Yo‘ldoshi","mafia","Town yo‘ldoshiga o‘xshab bloklaydi."],
  ["witch","Jodugar","neutral","Nishonni boshqa o‘yinchiga buradi."],
  ["serial_killer","Serial Killer","neutral","Yolg‘iz qolgan holda g‘alaba qilishga urinadi."],
  ["jester","Masxaraboz","neutral","O‘zini kunduz ovozida chiqarishga urinadi."],
  ["survivor","Omon qoluvchi","neutral","Oxirigacha tirik qolsa g‘alaba qiladi."],
  ["executioner","Jallod","neutral","Belgilangan nishonni ovoz bilan chiqarishga urinadi."],
  ["arsonist","O‘t qo‘yuvchi","neutral","Nishonlarni belgilab, keyin yoqadi."],
  ["vampire","Vampir","neutral","Alohida guruh sifatida o‘yinchilarni aylantiradi."],
  ["cultist","Kultchi","neutral","O‘yinchilarni o‘z guruhiga qo‘shishga urinadi."],
  ["thief","O‘g‘ri","neutral","Boshlanishda rol yoki kuchni o‘zgartiradi."],
  ["amnesiac","Xotirasiz","neutral","Keyinchalik o‘lgan rolni qabul qilishi mumkin."],
  ["illusionist","Illyuzionist","neutral","Tekshiruvlarni chalg‘itadi."],
  ["guardian","Himoyachi","town","Bir marta o‘zini qurbon qilib himoya qiladi."],
  ["spy","Ayg‘oqchi","town","Mafiya harakatlari haqida signal oladi."],
  ["alchemist","Alkimyogar","neutral","Cheklangan bir martalik iksirlar ishlatadi."],
  ["timekeeper","Vaqt qo‘riqchisi","town","Bir fazani maxsus tarzda boshqaradi."],
  ["priest","Ruhoniy","town","Bir marta la’nat yoki hujumni tozalaydi."],
  ["blacksmith","Temirchi","town","Bir himoya buyumini yaratadi."],
  ["gambler","Qimorboz","neutral","Tasodifiy shartli bonus oladi."]
]
  .map(([id,name,team,description])=>({id,name,team,description}));

function get(id){return roles.find(r=>r.id===id)||null;}
function all(){return roles.slice();}
function byTeam(team){return roles.filter(r=>r.team===team);}
function count(){return roles.length;}
function format(id){const r=get(id);return r?`🎭 ${r.name}\n👥 Team: ${r.team}\n📝 ${r.description}`:"Role topilmadi.";}
module.exports={roles,get,all,byTeam,count,format};
