services:
  - type: web
    name: pro-utag-bot
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    sourceDir: .
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        value: "6391842049"
      - key: ADMIN_USERNAME
        value: "@owapro"
      - key: DB_FILE
        value: "/app/data/database22.db"
      - key: PORT
        value: "10000"
      - key: SEND_SELF_TO_ADMIN
        value: "1"